simulator:
  n_agents: 10
  horizon: 30
  time_steps: 100
  dt: 0.05
  init_arena_range: [-3.0, 3.0]
  init_type: "origin"
  goal_threshold: 0.2
  device: "cpu"
  optimization_iters: 50
  step_size: 0.002
  W: [100.0, 5.0, 0.1, 1.0] # w1 = collision, w2 = collision cost exp decay, w3 = control, w4 = navigation
  Q: [0.1, 0.1, 0.001, 0.001] # Higher position weights
  R: [0.01, 0.01]

masking:
  limit_past_horizon: True
  mask_horizon: 10
  masking_method: "MLP"
  masking_model_path: "log/psn_N_10_T_50_obs_10_ref_50_lr_0.001_bs_32_sigma1_1.5_sigma2_1.0_sigma3_20.0_epochs_30/psn_best_model.pkl"
  top_k: 5
  critical_radius: 2.0