model_type: "mlp"
epochs: 100
batch_size: 32
learning_rate: 0.001
n_agents: 10
mask_horizon: 10
optimization_iters: 20
state_dim: 4
random_seed: 42
sigma_1: 0.0 # weight for sparsity |M| / N for loss in NN
sigma_2: 1000.0 # weight for trajectory loss in NN
# sigma_3: 1.0 # weight for collision loss in NN
dataset_dir: "src/data/mlp_n_agents_10_test"
max_grad_norm: 1.0

# Dynamics and cost parameters
dt: 0.1
step_size: 0.002
Q: [0.1, 0.1, 0.001, 0.001] # State cost weights (position, velocity)
R: [0.01, 0.01] # Control cost weights
W: [100.0, 5.0, 0.1, 1.0] # [collision weight, collision decay, control weight, navigation weight]