model_type: "mlp"
epochs: 10
learning_rate: 0.001
batch_size: 16
n_agents: 10
mask_horizon: 10
state_dim: 4
random_seed: 42
sigma_1: 1.5 # weight for sparsity |M| / N for loss in NN
sigma_2: 11 # weight for trajectory loss in NN
dataset_dir: "src/data/mlp_n_agents_10_test"